package com.bibli.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LibraryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryAllPropertiesEquals(Library expected, Library actual) {
        assertLibraryAutoGeneratedPropertiesEquals(expected, actual);
        assertLibraryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryAllUpdatablePropertiesEquals(Library expected, Library actual) {
        assertLibraryUpdatableFieldsEquals(expected, actual);
        assertLibraryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryAutoGeneratedPropertiesEquals(Library expected, Library actual) {
        assertThat(actual)
            .as("Verify Library auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryUpdatableFieldsEquals(Library expected, Library actual) {
        assertThat(actual)
            .as("Verify Library relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryUpdatableRelationshipsEquals(Library expected, Library actual) {
        // empty method
    }
}
